//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

public interface IApp
{
    string Name { get; set; }

    string Key { get; set; }

    void RegisterFunctionCategory(IFunctionCategory fn);

    void CancellationFunctionCategory(IFunctionCategory fn);

    List<IFunctionCategory> FunctionCategorys { get; set; }

}

