//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

public interface IFunctionCategory
{
    object Name { get; set; }

    object Summary { get; set; }

    List<IFunction> Functions { get; set; }

    void RemoveFunction(IFunction fn);

    void AddFunction(IFunction fn);

}

