//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------

public interface IFunction
{
    string Name { get; set; }

    string Summary { get; set; }

    IFunctionCategory FunctionCategory { get; set; }

}

