//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

public interface IOrganization
{
    OrganizationType Type { get; set; }

    string Name { get; set; }

    string FullName { get; set; }

    string ParentId { get; set; }

    bool IsHidden { get; set; }

    List<IUser> Users { get; set; }

    void AddUser(IUser user);

    void RemoveUser(IUser user);

    List<IPosition> Positions { get; }

    void RemovePosition(IPosition pos);

    void AddPosition(IPosition pos);

    void AddChild(IOrganization org);

    List<IOrganization> Children { get; }

    void RemoveChild(IOrganization org);

    void AddUser(IUser user, string posId);

}

