//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

public interface IRole
{
    string Name { get; set; }

    string Summary { get; set; }

    List<IUser> Users { get; }

    void RemoveUser(IUser user);

    void AddUser(IUser user);

    List<IFunction> Functions { get; }

    void AddFunction(IFunction fn);

    void RemoveFunction(IFunction fn);

    void AddScope(IScope sp);

    List<IScope> Scopes { get; }

    void RemoveScope(IScope sp);

    void AddOrganization(IOrganization org);

    List<IOrganization> Organizations { get; }

    void RemoveOrganization(IOrganization org);

    List<IPosition> Positions { get; }
}

