//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

public interface IScope
{
    string Name { get; set; }

    object Summary { get; set; }

    string Value { get; set; }

    string ParentId { get; set; }

    void AddChild(IScope child);

    void RemoveChild(IScope child);

    List<IScope> Children { get; }
}

