//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

public interface IUser
{
    string Account { get; set; }

    string Name { get; set; }

    string Title { get; set; }

    IUser Auth(IUser user);

    List<IRole> Roles { get; }

    List<IFunction> GetFunction(IScope sp);

    bool CheckFunction(string fnId, string spId);

    List<IOrganization> Organizations { get; }

    IPosition GetPosition(string orgId);

}

